### ISSUE TITLE
Autowiring based on implemented interface

### ISSUE THREAD

**Issue by jakubkulhan** [skrz/autowiring-bundle#3]
- Primarily for `*AwareInterface`s, e.g. `Symfony\Component\DependencyInjection\ContainerAwareInterface` implemented by non-application ("other people's") code.
- Supposed syntax:

``` yaml
autowiring:
  interfaces:
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - [setContainer, [@service_container]]
```
- Should be called `interfaces`? Could also autowire to methods of abstract classes.
- Could expose interface to other bundles (i.e. yet-to-be-released `Skrz\Bundle\TemplatingBundle`) - how?
